name: Employee Website CI/CD

# Trigger on push or PR to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build Docker image
      - name: Build Docker image
        run: docker build -t employee-website:latest .

      # Step 3: Test Docker image
      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 --name test-employee employee-website:latest
          docker ps
